# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    firewalls:
        app:
            pattern: ^/app/
            provider: users
            anonymous: true
            form_login:
                login_path: app_login
                check_path: app_login_check
                default_target_path: game_list
                always_use_default_target_path: true
            logout:
                path: app_logout
                target: landing
            switch_user: { role: ROLE_ADMIN }
    access_control:
        - { path: ^/app/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app, roles: [ROLE_TEACHER, ROLE_ADMIN] }
    providers:
        users:
            entity:
                class: AppBundle\Entity\User
                property: email
    encoders:
        AppBundle\Entity\User: bcrypt
